spring:
  application:
    name: artemis-test
  flyway:
    enabled: false
    default-schema: test
    schemas: ${spring.flyway.default-schema}
  artemis:
  #  mode: embedded
  #  host: localhost
  #  port: 61616
  #  user: developer
  #  password: developer
    embedded:
      enabled: true

java:
  util:
    logging:
      manager: none

my:
  schema: test

zonky:
  test:
    database:
      postgres:
        client:
          properties:
            stringtype: unspecified
            currentSchema: test
        server:
          properties:
            shared_buffers: 16MB
            max_connections: 20

jms:
  queue:
    destination: test

route:
  start: direct:start
  end: direct:end

camel:
  component:
    direct:
      timeout: 1000
      block: true